from setuptools import setup, find_packages

setup(
    name="research-hippo-with-products",
    version="0.1.0",
    package_dir={"": "src"},
    packages=find_packages(where="src"),
    install_requires=[
        "appnope",
        "asttokens",
        "attrs",
        "comm",
        "contourpy",
        "cycler",
        "debugpy",
        "decorator",
        "executing",
        "fastjsonschema",
        "filelock",
        "finufft",
        "fonttools",
        "fsspec",
        "ipykernel",
        "ipython",
        "jedi",
        "Jinja2",
        "joblib",
        "jsonschema",
        "jsonschema-specifications",
        "jupyter_client",
        "jupyter_core",
        "kaleido",
        "kiwisolver",
        "MarkupSafe",
        "matplotlib",
        "matplotlib-inline",
        "mpmath",
        "nbformat",
        "nest-asyncio",
        "networkx",
        "numpy",
        "packaging",
        "parso",
        "pexpect",
        "pillow",
        "platformdirs",
        "plotly",
        "prompt_toolkit",
        "psutil",
        "ptyprocess",
        "pure_eval",
        "Pygments",
        "pynufft",
        "pyparsing",
        "python-dateutil",
        "pyzmq",
        "referencing",
        "rpds-py",
        "scikit-learn",
        "scipy",
        "setuptools",
        "six",
        "stack-data",
        "sympy",
        "tenacity",
        "threadpoolctl",
        "torch",
        "tornado",
        "tqdm",
        "traitlets",
        "typing_extensions",
        "wcwidth",
    ],
    extras_require={
        "dev": [
            "pytest",
            "flake8",
            "black",
            "isort",
            "mypy",
            "pre-commit",
        ],
    },
    author="Your Name",
    author_email="your.email@domain.com",
    description="Research project on hippocampus with associated products.",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/stash-196/research-hippo-with-products",
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    python_requires=">=3.12",
)
